server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
    application:
      name: service-user
    profiles:
      active: dev
    config:
      import: "optional:configserver:http://admin:12345678@localhost:8002"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always