server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
    application:
      name: gateway-server
    main:
      web-application-type: reactive




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${server.port}



management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always