#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: user-service
#          uri: lb://service-user
#          predicates:
#            - Path=/u/**
#        - id: company-service
#          uri: lb://service-company
#          predicates:
#            - Path=/c/**


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-company
          uri: lb://service-company  # 使用服务名
          predicates:
            - Path=/c/**
        - id: service-user
          uri: lb://service-user  # 使用服务名
          predicates:
            - Path=/u/**
